# Generated by Django 4.0.4 on 2022-10-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_carousel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_long',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
