# Generated by Django 4.0.4 on 2022-10-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_artist_about_alter_news_desc_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc_long',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
