# Generated by Django 4.0.4 on 2022-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_perfil_discord_alter_perfil_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
