# Generated by Django 4.0.4 on 2022-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_about_coreteam_carousel_image_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
