# Generated by Django 4.0.4 on 2022-11-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_about_is_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coreteam',
            old_name='desc',
            new_name='description',
        ),
    ]
