# Generated by Django 4.0.4 on 2022-11-22 14:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_coreteam_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
