# Generated by Django 4.0.4 on 2022-12-05 17:57

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_artist_id_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contract', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', tinymce.models.HTMLField()),
                ('coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('date_event', models.DateTimeField()),
                ('location_event', models.CharField(blank=True, max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('link_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('link_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('link_facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.artist')),
            ],
        ),
    ]
