# Generated by Django 4.0.4 on 2022-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='id_contract',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
