# Generated by Django 4.0.4 on 2022-12-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_events_id_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location_desc',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
