# Generated by Django 4.0.4 on 2022-12-05 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_events_id_contract_eventticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='event',
        ),
        migrations.AddField(
            model_name='eventticket',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.events'),
        ),
    ]
