# Generated by Django 4.0.4 on 2022-12-05 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_eventticket_event_eventticket_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.events'),
        ),
    ]
