# Generated by Django 4.0.4 on 2022-12-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_eventticket_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.artist'),
        ),
    ]
