# Generated by Django 4.0.4 on 2022-12-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_nftmedia_artista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftmedia',
            old_name='artista',
            new_name='artist',
        ),
    ]
