# Generated by Django 4.0.4 on 2022-12-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_rename_artista_nftmedia_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftmedia',
            old_name='media',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='nftmedia',
            old_name='name',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='nftmedia',
            name='tier',
        ),
        migrations.AlterField(
            model_name='nftmedia',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.artist'),
        ),
    ]
