# Generated by Django 4.0.4 on 2022-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_userdiscord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscord',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
