# Generated by Django 4.0.4 on 2023-02-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_suscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='serie_ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
