# Generated by Django 4.0.4 on 2023-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_events_serie_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='account_near',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artist',
            name='account_near_tax',
            field=models.CharField(default='', max_length=255),
        ),
    ]
