# Generated by Django 4.0.4 on 2023-03-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_artist_account_near_artist_account_near_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiersAvalaible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierOne', models.BooleanField(default=False)),
                ('tierTwo', models.BooleanField(default=False)),
                ('tierThree', models.BooleanField(default=False)),
                ('tierFour', models.BooleanField(default=False)),
                ('tierFive', models.BooleanField(default=False)),
                ('tierSix', models.BooleanField(default=False)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.artist')),
            ],
        ),
    ]
