# Generated by Django 4.0.4 on 2023-03-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_tiersavalaible'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiersAvalaible',
            new_name='TiersComingSoon',
        ),
    ]
