# Generated by Django 4.0.4 on 2023-03-20 15:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_rename_tiersavalaible_tierscomingsoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=tinymce.models.HTMLField(),
        ),
    ]
