# Generated by Django 4.0.4 on 2023-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_alter_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
