# Generated by Django 4.0.4 on 2023-03-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_artistsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscribe',
            new_name='Subscribe',
        ),
    ]
