# Generated by Django 4.0.4 on 2023-03-31 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_remove_artist_account_near_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscord',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
