# Generated by Django 4.0.4 on 2023-06-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_orderredeem'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
