# Generated by Django 4.0.4 on 2023-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_orderredeem_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderredeem',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderredeem',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
