# Generated by Django 4.0.4 on 2023-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_orderredeem_email_orderredeem_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveNft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(default='', max_length=255)),
                ('token_id', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
