# Generated by Django 4.0.4 on 2023-06-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_drivenft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivenft',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderredeem',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
