# Generated by Django 4.0.4 on 2023-10-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('about', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('banner_mobile', models.ImageField(blank=True, null=True, upload_to='')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('discord', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.PositiveIntegerField(default=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TierProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierNumber', models.PositiveIntegerField()),
                ('nft_name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=255)),
                ('copies', models.PositiveIntegerField()),
                ('status', models.PositiveIntegerField(default=3)),
                ('media', models.CharField(blank=True, max_length=255, null=True)),
                ('royalties', models.CharField(blank=True, max_length=255, null=True)),
                ('artist_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.artistproposal')),
            ],
        ),
    ]
