# Generated by Django 4.0.4 on 2023-10-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_artistproposal_tierproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistproposal',
            name='wallet_artist',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artistproposal',
            name='wallet',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
