# Generated by Django 4.0.4 on 2023-12-22 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_artistproposal_tierproposal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bio',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='discord',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='tierproposal',
            old_name='media',
            new_name='royalties_split',
        ),
        migrations.RemoveField(
            model_name='tierproposal',
            name='copies',
        ),
        migrations.AddField(
            model_name='artist',
            name='creator_id',
            field=models.CharField(default='everyone_eats_entertainment.near', max_length=255),
        ),
        migrations.AddField(
            model_name='artistproposal',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='artistproposal',
            name='id_collection',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artistproposal',
            name='wallet_artist',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='nftmedia',
            name='number_collection',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='perfil',
            name='banner_artist',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tierproposal',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tierproposal',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tierscomingsoon',
            name='number_collection',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='artistproposal',
            name='wallet',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nftmedia',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.artist'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tierscomingsoon',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.artist'),
        ),
    ]
