# Generated by Django 4.0.4 on 2024-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_rename_bio_perfil_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftmedia',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
