# Generated by Django 4.0.4 on 2023-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_artistproposal_wallet_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistproposal',
            name='id_collection',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
