# Generated by Django 4.0.4 on 2023-10-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_artistproposal_id_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierproposal',
            name='royalties_split',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
