# Generated by Django 4.0.4 on 2023-10-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_tierproposal_royalties_split'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tierproposal',
            old_name='media',
            new_name='video',
        ),
        migrations.AddField(
            model_name='tierproposal',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
