# Generated by Django 4.0.4 on 2023-10-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_rename_media_tierproposal_video_tierproposal_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tierproposal',
            name='copies',
        ),
    ]
