# Generated by Django 4.0.4 on 2023-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_artistproposal_tierproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='creator_id',
            field=models.CharField(
                default='musicfeast.testnet', max_length=255),
        ),
    ]
