# Generated by Django 4.0.4 on 2023-10-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_remove_tierproposal_copies'),
        ('backend', '0061_artist_creator_id'),
    ]

    operations = [
    ]
