# Generated by Django 4.0.4 on 2023-10-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_merge_20231025_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftmedia',
            name='number_collection',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nftmedia',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.artist'),
        ),
    ]
