# Generated by Django 4.0.4 on 2023-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_nftmedia_number_collection_alter_nftmedia_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
