# Generated by Django 4.0.4 on 2023-11-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_perfil_banner_mobile_perfil_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='banner_artist',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
